#!/usr/bin/env python
import csv
import os
import Cookie
import datetime

lineas = []
usuarios = 0
clave = 'idesesion'
if 'HTTP_COOKIE' in os.environ:
    cookie_string = os.environ.get('HTTP_COOKIE')
    c = Cookie.SimpleCookie()
    c.load(cookie_string)
    with open('usuarios.csv', 'r') as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            lineas.append(row)
            try:
                if c['idsesion'].value == row['idsesion']:
                    clave = 'idsesion'
                    valor = row['idsesion']
            except KeyError:
                pass

    with open('usuarios.csv', 'w') as csvfile:
        writer = csv.writer(csvfile)
        writer.writerow(["nick","numero_mensaje","idsesion"])
        for linea in lineas:
            if not linea['idsesion'] == valor:
                writer.writerow([linea['nick'],linea['numero_mensaje'],linea['idsesion']])
    
    with open('usuarios.csv', 'r') as csvfile:
        usuarios = len(csvfile.readlines())

    if usuarios <= 2:
        with open('mensajes.csv', 'w') as csvfile:
            writer = csv.writer(csvfile)
            writer.writerow(["id","nick","mensaje"])
    print("Set-Cookie: {}={}; expires=Thu, 01 Jan 1970 00:00:00 GMT".format(clave,valor))
    print("Content-type: text/html\n\n")    
    print("<HTML><BODY>\n")
    print("<meta http-equiv=\"refresh\" content=\"0; URL='http://localhost/Chat-CGI-JS/index.html'\" />")
    print("</HTML></BODY>\n")