#!/usr/bin/python
import cgi
import csv
form = cgi.FieldStorage()
nickU = form.getvalue('nick')
logueo = True
with open('usuarios.csv', 'r') as archivocsv:
    reader = csv.DictReader(archivocsv)
    for row in reader:
        if (row['nick'] == nickU):
            logueo = False
if logueo == True:
    with open('usuarios.csv', 'a') as csvfile:
        fieldnames = ['nick']
        writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
        writer.writerow({'nick': nickU})
    mensaje = "Bienvenido {0}".format(nickU)
else:
    mensaje = "Este usuario ya se encuentra en la sala de chat"
print("Content-type: text/plain\n\n")
print("{0}".format(mensaje))
