#!/usr/bin/python
import cgi
import csv
import Cookie
import os

if 'HTTP_COOKIE' in os.environ:
    cookie_string = os.environ.get('HTTP_COOKIE')
    c=Cookie.SimpleCookie()
    c.load(cookie_string)
    with open('usuarios.csv', 'r') as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            try:
                if c[row['nick']]: 
                    ultimo_mensaje_enviado = int(c[row['nick']].value)
                    with open('mensajes.csv', 'r') as csvfile1:
                        nuevo_ultimo_mensaje = sum(1 for row in csvfile1)
                    c[row['nick']] = nuevo_ultimo_mensaje                   
            except KeyError:
                pass
    print(c)
print("Content-type: text/html\n\n")
with open('mensajes.csv', 'r') as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            if row['id'] > ultimo_mensaje_enviado:
                print("<li class=\"left clearfix\"><span class=\"chat-img pull-left\">")
                print("<img src=\"http://192.168.2.75/Chat-CGI-JS/img/{}.png\" class=\"img-circle\"  height=\"50px\" width=\"50px\"/>".format(row['nick']))
                print("</span>")
                print("<div class=\"chat-body clearfix\">")
                print("<div class=\"header\">")
                print("<strong class=\"primary-font\">{}</strong> <small class=\"pull-right text-muted\">".format(row['nick']))
                print("</div>")
                print("<p>")
                print("{}".format(row['mensaje']))
                print("</p></div></li>")