#!/usr/bin/python
import cgi
import csv
form = cgi.FieldStorage()
nickU = form.getvalue('nick')
with open('usuarios.csv', 'r') as archivocsv:
    reader = csv.DictReader(archivocsv)
    logueo = True
    for row in reader:
        if (row['nick'] == nickU):
            logueo = False
print("Content-type: text/html\n\n")
print("<html><head><title>CGI</title></head>")
print("<body>")
if logueo == True:
    with open('usuarios.csv', 'a') as csvfile:
        fieldnames = ['nick']
        writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
        writer.writerow({'nick': nickU})
    print("OK")
else:
    print("Nombre en Uso")
print("</body>")
print("</html>")
